name: neo_player
description: Audio player app build with flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ################################ UI PACKAGES #################################

  # Icons for IOS
  cupertino_icons: ^1.0.2

  # Neumorphic ui kit for Flutter.
  flutter_neumorphic: ^3.2.0

  # Easy and Fast internationalizing and localization.
  easy_localization: ^3.0.1

  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^1.1.0

  # An SVG rendering
  flutter_svg: ^1.1.0

  # Toast Library for Flutter
  fluttertoast: ^8.0.9

  # Loading indicators animated
  flutter_spinkit: ^5.1.0

  ########################## DATA PERSISTENCE PACKAGES #########################

  # Flutter plugin for reading and writing simple key-value pairs.
  shared_preferences: ^2.0.15

  # Adds SQLite support with Data Access Objects and streams
  sqflite: ^2.0.2+1

  ############################### OTHER PACKAGES ###############################

  # Request and check permissions.
  # permission_handler: ^10.0.0

  # Supplies the app with the directory location for storing files
  path_provider: ^2.0.11
  path: ^1.8.0

  # A Flutter plugin for launching a URL.
  # url_launcher: ^6.1.4

  # Querying information about an application package.
  # package_info_plus: ^1.4.2

  # Get current device information
  # device_info_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Defines files available to the app
  assets:
    - assets/
    #    - assets/icons/
    #    - assets/images/
    - assets/locales/
    - assets/google_fonts/

  # Specifies fonts and their respective font weights (thickness)
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/google_fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Nunito-Black.ttf
          weight: 900